services:
  mysql-server:
    image: mysql:8
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: shopping_cart
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 20s
      retries: 3
      start_interval: 3s
    ports:
      - "7000:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - mysql-network

  mysql-client:
    image: phpmyadmin/phpmyadmin
    container_name: mysql-client
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    depends_on:
      mysql-server:
        condition: service_healthy
    networks:
      - mysql-network
    
volumes:
  mysql-volume:
    name: mysql-volume

networks:
  mysql-network:
    name: mysql-network